Name:           ros-melodic-linux-networking
Version:        1.0.15
Release:        0%{?dist}
Summary:        ROS linux_networking package

Group:          Development/Libraries
License:        TODO
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-access-point-control
Requires:       ros-melodic-asmach
Requires:       ros-melodic-asmach-tutorials
Requires:       ros-melodic-ddwrt-access-point
Requires:       ros-melodic-hostapd-access-point
Requires:       ros-melodic-ieee80211-channels
Requires:       ros-melodic-linksys-access-point
Requires:       ros-melodic-multi-interface-roam
Requires:       ros-melodic-network-control-tests
Requires:       ros-melodic-network-detector
Requires:       ros-melodic-network-monitor-udp
Requires:       ros-melodic-network-traffic-control
BuildRequires:  ros-melodic-catkin

%description
The linux_networking package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Mar 30 2019 Devon Ash <dash@clearpathrobotics.com> - 1.0.15-0
- Autogenerated by Bloom

* Wed Mar 06 2019 Devon Ash <dash@clearpathrobotics.com> - 1.0.13-2
- Autogenerated by Bloom

* Wed Mar 06 2019 Devon Ash <dash@clearpathrobotics.com> - 1.0.13-1
- Autogenerated by Bloom

* Wed Mar 06 2019 Devon Ash <dash@clearpathrobotics.com> - 1.0.13-0
- Autogenerated by Bloom

