%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-multi-interface-roam
Version:        1.1.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS multi_interface_roam package

License:        BSD
URL:            http://ros.org/wiki/multi_interface_roam
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-twisted
Requires:       ros-noetic-asmach
Requires:       ros-noetic-diagnostic-msgs
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-ieee80211-channels
Requires:       ros-noetic-network-monitor-udp
Requires:       ros-noetic-pr2-msgs
Requires:       ros-noetic-rospy
Requires:       ros-noetic-std-msgs
BuildRequires:  ros-noetic-asmach
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-diagnostic-msgs
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-ieee80211-channels
BuildRequires:  ros-noetic-network-monitor-udp
BuildRequires:  ros-noetic-pr2-msgs
BuildRequires:  ros-noetic-rospy
BuildRequires:  ros-noetic-std-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
sdsdddsdsds

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Mar 02 2021 Devon Ash <dash@clearpathrobotics.com> - 1.1.0-1
- Autogenerated by Bloom

